@ECommerce.Catalog.API_HostAddress = https://localhost:7203

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJSb2xlIHsgTmFtZSA9IFVzZXIgfSIsInN1YiI6ImYzODdhODhiLTUwNDMtNGFmZS04ODJjLWQ3OTAzN2M2YjUwZSIsIm5iZiI6MTczNjc3MjI0NiwiZXhwIjoxNzM2Nzc1ODQ2LCJpc3MiOiJpZGVudGl0eS1zZXJ2aWNlIiwiYXVkIjoiY2xpZW50In0.pW0qvLE07mm7XqyueoNiedmRf_pQx2E13idRxhoDyWg
GET {{ECommerce.Catalog.API_HostAddress}}/products
Authorization: Bearer {{token}}

###

@productId=3f95ca6a-fa07-4251-92d9-0cdb70fd9172
@discount=0.10
PUT {{ECommerce.Catalog.API_HostAddress}}/products/{id}/discount/{{discount}}?productId={{productId}}

###
